Update refs to Java 8 to Java 11 as min version
fluree/docs.flur.ee pull request #14
Opened 2021-04-16 14:18 UTC by Tr3yb0

2021-04-16 14:24 UTC, ldw1007 requested changes
Let me know if you need help creating a new "anywhere.md" file for v1.0

2021-04-16 14:24 UTC, ldw1007 commented on src/content/0.15.0/docs/start/anywhere.md
> +To run Fluree, you need Java 11 or above. To verify your version of Java, you can type `java -version` in the terminal.
Actually, v0.15 & v0.16 were tested/running under Java 8.  
You need to create a copy of this file for v1.0

2021-04-16 14:24 UTC, ldw1007 commented on src/content/0.15.0/docs/start/anywhere.md
> +If the above message is not displaying in your terminal, the terminal should print out a relevant error message. Common errors include your chosen port already being in use and not having Java 11 or
same comment as above - changes need to be in a new file for v1.0

2021-04-16 14:24 UTC, ldw1007 commented on src/content/0.15.0/docs/start/anywhere.md
> +- If you see an error "missing 'server' JVM", you need to install Java Server JRE. See <a href="https://docs.oracle.com/en/java/" target="_blank">Oracle documentation</a> to select the appropriate pl
:) same comment.

2021-04-16 19:52 UTC, Tr3yb0 reviewed
corrected issues

2021-04-16 20:04 UTC, ldw1007 commented on src/content/0.15.0/docs/start/anywhere.md
> +If the above message is not displaying in your terminal, the terminal should print out a relevant error message. Common errors include your chosen port already being in use and not having Java 11 or
actually, this needs to be changed to Java 11

2021-04-19 12:59 UTC, ldw1007 approved these changes

2021-04-19 12:59 UTC, merged